services:
  fastapi:
    container_name: fastapi
    build:
      context: ../  # Set the context to the project root directory
      dockerfile: deploy_mlflow/Dockerfile.Fastapi  # Specify the path to Dockerfile within the context
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3

  mlflow:
    container_name: mlflow
    build:
      context: ../
      dockerfile: deploy_mlflow/Dockerfile.Mlflow  # Specify the Dockerfile for MLflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///app/deploy_mlflow/mlruns/mlflow.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
