name: Build and Deploy lambda

on:
  workflow_dispatch:
    inputs:
      push_to_ecr:
        description: 'Push the Docker image to AWS ECR'
        required: true
        default: 'false'
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: sqlite:///app/deploy_mlflow/mlruns/mlflow.db
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub (optional if not needed for this workflow)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 3: Set up Docker
    - name: Set up Docker
      run: |
        docker --version

    # Step 4: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 5: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    # Step 6: Build and tag Docker image
    - name: Build and tag Docker image
      run: |
        docker build -t image-classification-app -f ./deploy_lambda/dockerfile.lambda .
        docker tag image-classification-app:latest localhost:5000/image-classification-app:latest

    # Step 7: Push the image to Amazon ECR
    - name: Push Docker image to Amazon ECR or Local Registry
      run: |
        if [ "${{ github.event.inputs.push_to_ecr }}" == "true" ]; then
          docker tag image-classification-app:latest $ECR_REGISTRY/image-classification-app:latest
          docker push $ECR_REGISTRY/image-classification-app:latest
        else
          docker push localhost:5000/image-classification-app:latest
        fi

    # Step 8: Update the Lambda function
    - name: Update Lambda function
      if: github.event.inputs.push_to_ecr == 'true'
      run: |
        aws lambda update-function-code \
          --function-name image-classification-model \
          --image-uri $ECR_REGISTRY/image-classification-app:latest \
          --region $AWS_REGION
