name: Build and Deploy MLflow-FastAPI

on:
  push:
    paths:
      - "deploy_mlflow/**"  # Trigger only on changes to the deploy_mlflow directory
      - ".github/workflows/build_deploy_mlflow.yml"  # Trigger if this workflow is updated
  pull_request:
    paths:
      - "deploy_mlflow/**"
      - ".github/workflows/build_deploy_mlflow.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Docker (Docker is pre-installed on GitHub runners)
    - name: Set up Docker
      run: docker --version  # Validate Docker is installed

    # 3. Install docker-compose manually
    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Validate docker-compose is installed

    # 4. Build the Docker image for mlflow-fastapi
    - name: Build Docker image
      run: |
        cd deploy_mlflow
        docker compose build  # Use `docker compose` instead of `docker-compose`

    # 5. Run the container for testing
    - name: Run container
      run: |
        cd deploy_mlflow
        docker compose up -d
        sleep 20  # Allow services to start

    # 6. Test services using service names
    - name: Test FastAPI service
      run: |
        curl --fail http://fastapi:8000/docs  # Test FastAPI docs endpoint

    - name: Test MLflow UI
      run: |
        curl --fail http://mlflow:5000  # Test MLflow UI

    - name: Output logs for debugging
      if: failure()
      run: |
        cd deploy_mlflow
        docker compose logs
        
    # 7. Tear down running containers
    - name: Stop and remove containers
      if: always()
      run: |
        cd deploy_mlflow
        docker compose down
